name: azure-terraform-infra-testing-purpose

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
      - 'hotfix/**'

jobs:
  terraforminit:
    name: terraform init
    runs-on: ubuntu-latest

    steps:
      - name: azure-terraform-infra
        run: echo "azure-terraform-infra bhai"
