name: "azure-terraform-infra"

on: 
  push: 
    branches: 
        - 'feature/**'
        - 'main'
        - 'hotfix/**'
        
jobs:
  terraforminit:
    name: terraform init
    runs-on: github-actions
    steps: 
    - name: "azure-terraform-infra"
      run: echo azure-terraform-infra
