name: "azure-terraform-infra"

on: workflow_dispatch

permissions: 
  id-token: write
  contents: read

jobs: 
  terraform-init-plan: 
    runs-on: self-hosted
    steps: 
      - name: checkout
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: # optional
        # ClientId of the Azure Service principal created.
        client-id: 
        # TenantId of the Azure Service principal created.
        tenant-id: 
        # Azure subscriptionId
        subscription-id: 
           
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-dirictory: environments/dev
      
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-dirictory: environments/dev
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-dirictory: environments/dev
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        
    terraform-Apply: 
      runs-on: self-hosted\
      needs: terraform-init-plan
      environments: dev
        steps: 
          - name: checkout
          - uses: actions/checkout@v4
          
          - name: Azure Login
            uses: Azure/login@v2.3.0
            with:
            # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
            creds: # optional
            # ClientId of the Azure Service principal created.
            client-id: 
            # TenantId of the Azure Service principal created.
            tenant-id: 
            # Azure subscriptionId
            subscription-id: 

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-dirictory: environments/dev

      - name: Terraform apply
        id: appy
        run: terraform apply --auto--approve
        continue-on-error: true
        working-dirictory: environments/dev
        
