name: "azure-terraform-infra"

on: workflow_dispatch

permissions: 
  id-token: write
  contents: read

jobs: 
  terraform-job: 
    runs-on: self-hosted
    steps: 
      - name: checkout
      - uses: actions/checkout@v4
      
      - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: # optional
        # ClientId of the Azure Service principal created.
        client-id: 
        # TenantId of the Azure Service principal created.
        tenant-id: 
        # Azure subscriptionId
        subscription-id: 
           
